### ISSUE TITLE
Provide a pip freeze of python dependencies for debugging purposes 

### ISSUE THREAD

**Issue by luisberlioz** [gerby-project/gerby-project.github.io#1]
Is it possible for the project's admins to provide a pip freeze of a working environment. 
The reason for this is that, after trying the instructions on this webpage with no success, some of us believe that a recent upgrade broke the building process.
As an example of the problems we are seeing when running the gerby-project version of plastex:

 plasTeX version 1.0
ERROR: An error occurred while building the document object in <tokens> on
   line 1 (generator raised StopIteration)
ERROR: Error while reading argument "options" of documentclass in <string>
   on line 1 (generator raised StopIteration)
ERROR: Error while expanding "documentclass" in <string> on line 1
   (generator raised StopIteration)
ERROR: An error occurred while building the document object in <string> on
   line 1 (generator raised StopIteration)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/plasTeX/Tokenizer.py", line 388, in _iter_
    token = next(charIter)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/plastex", line 142, in <module>
    main(sys.argv)
  File "/usr/bin/plastex", line 90, in main
    tex.parse()
  File "/usr/lib/python3.7/site-packages/plasTeX/TeX.py", line 439, in parse
    for item in tokens:
  File "/usr/lib/python3.7/site-packages/plasTeX/TeX.py", line 46, in _next_
    return self._next()
  File "/usr/lib/python3.7/site-packages/plasTeX/TeX.py", line 347, in _iter_
    tokens = obj.invoke(self)
  File "/usr/lib/python3.7/site-packages/plasTeX/Base/LaTeX/Packages.py", line 36, in invoke
    a = self.parse(tex)
  File "/usr/lib/python3.7/site-packages/plasTeX/_init_.py", line 472, in parse
    **arg.options)
  File "/usr/lib/python3.7/site-packages/plasTeX/TeX.py", line 761, in readArgumentAndSource
    toks, source = self.readGrouping(spec, expanded, parentNode=parentNode)
  File "/usr/lib/python3.7/site-packages/plasTeX/TeX.py", line 913, in readGrouping
    toks = self.expandTokens(toks, parentNode=parentNode)
  File "/usr/lib/python3.7/site-packages/plasTeX/TeX.py", line 410, in expandTokens
    out = tex.parse(frag)
  File "/usr/lib/python3.7/site-packages/plasTeX/TeX.py", line 439, in parse
    for item in tokens:
  File "/usr/lib/python3.7/site-packages/plasTeX/TeX.py", line 46, in _next_
    return self._next()
  File "/usr/lib/python3.7/site-packages/plasTeX/TeX.py", line 326, in _iter_
    token = next()
  File "/usr/lib/python3.7/site-packages/plasTeX/TeX.py", line 267, in itertokens
    t = next(inputs[-1][-1])
RuntimeError: generator raised StopIteration

**Comment by pbelmans** [comment]
Here is a `pip freeze` with lots of junk in it (shame on me for not using separate environments):

```
alabaster==0.7.12
appdirs==1.4.3
arxiv2bib==1.0.8
attrs==18.1.0
Babel==2.6.0
beautifulsoup4==4.6.1
bibgetter==0.2
black==18.6b4
bleach==2.1.3
bs4==0.0.1
certifi==2018.4.16
chardet==3.0.4
click==6.7
decorator==4.3.0
docutils==0.14
EbookLib==0.17
feedparser==5.2.1
Flask==1.0.2
Flask-HTTPAuth==3.2.4
flask-profiler==1.6
Flask-Scss==0.5
html5lib==1.0.1
idna==2.7
imagesize==1.1.0
itsdangerous==0.24
Jinja2==2.10
latexcodec==1.0.5
libsass==0.14.5
lxml==4.2.5
Markdown==2.6.11
MarkupSafe==1.0
mdx-bleach==0.1.4
mr2bib==0.1
packaging==18.0
peewee==3.6.4
pybtex==0.21
Pygments==2.3.1
pyparsing==2.3.0
PyPDF2==1.26.0
pyScss==1.3.5
python-dateutil==2.7.3
python-markdown-math==0.6
pytz==2018.7
PyYAML==3.13
requests==2.19.1
selenium==3.14.1
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.8.3
sphinxcontrib-websupport==1.1.0
toml==0.9.4
urllib3==1.23
validators==0.12.2
webencodings==0.5.1
Werkzeug==0.14.1
```

Is this helpful?
